services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped

    ports:
      - "127.0.0.1:6333:6333"
      - "127.0.0.1:6334:6334"

    volumes:
      - qdrant_storage:/qdrant/storage

  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: python_teacher
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "127.0.0.1:15432:5432"

    volumes:
      - postgres_storage:/var/lib/postgresql/data

volumes:
  qdrant_storage:
  postgres_storage: